name: Nightly
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: pytest (Polars prerelease)
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          environments: nightly
      - name: Install latest Polars including prereleases
        run: pixi run -e nightly install-polars-nightly
      - name: Install repository
        run: pixi run -e nightly postinstall
      - name: Run pytest
        run: pixi run -e nightly test-coverage --color=yes
